### ISSUE TITLE
fail to download vgg_conv.pth

### ISSUE THREAD

**Issue by pean1128** [lukasHoel/stylemesh#2]
Hi, when I try to use this code with my data, I found that I can not download the vgg_conv.pth through the given link. Could you provide a mirror link to achieve this file, thanks a lot.

**Comment by lukasHoel** [comment]
Hi, thanks for reporting it, seems the website is down. Provided an alternative download here: https://drive.google.com/file/d/1IpTw7zOjWFMYXgt2zThPYIJ8c-DJw3xU/view?usp=sharing
