### ISSUE TITLE
Rendered Image is different with refered one.

### ISSUE THREAD

**Issue by pean1128** [lukasHoel/stylemesh#3]
Hi, I found the scan images and the rendered images are different. For example, the following image is 22.jpg in ScanNet scene "scene0291_00"
The top color image is extracted from the scanner and the bottom one is rendered by myself (Platform: MacOS). 
![22](https://user-images.githubusercontent.com/24985045/187578093-a77ab50e-156b-43bb-9a01-18e12a525df7.jpg)
![22 textured](https://user-images.githubusercontent.com/24985045/187578082-a9377408-a134-40de-9401-f53b9d597ee2.jpg)
My shell command to activate render is 
`
./scannet_uv_renderer 
./scene0291_00/scene0291_00_vh_clean_decimate_500000_uvs_blender.ply ./datasets/scannet/train/images/scene0291_00/pose 
./datasets/scannet/train/images/scene0291_00/scene0291_00.txt 
. 
0 320 240 
./datasets/scannet/train/scans/scene0291_00/epoch_3_texture.jpg
`
What's wrong with my operation? Look forward to your favourable reply.

**Comment by lukasHoel** [comment]
Hi, when I run the same command on the preprocessed sample data for `scene0291_00`, I get an output that matches the rgb image. Are you using the sample data for `scene0291_00` or did you preprocess it yourself? The pose that corresponds to image `22.jpg` should be stored in `./datasets/scannet/train/images/scene0291_00/pose/22.txt` and have the following content:

```
-0.876199 0.265493 -0.402230 4.310431
0.475371 0.338653 -0.811996 4.684800
-0.079363 -0.902678 -0.422935 1.354476
0.000000 0.000000 0.000000 1.000000
```
In other words, this is the pose that gives you the rendered image `22.textured.jpg` corresponding to `22.jpg`.

Perhaps make sure that your pose file matches this content?

Btw it is probably easier to use the python script that calls the renderer, it can be called with actual flags and makes it a bit easier to understand what stuff needs to be provided :) The command for it would be

`python render_mipmap_scannet.py --tex /absolute/path/to/tex_0_epoch_6_texture.jpg --mesh /absolute/path/to/scene0291_00_vh_clean_decimate_500000_uvs_blender.ply --poses /absolute/path/to/pose/ --intrinsics /absolute/path/to/scene0291_00.txt --renderer /absolute/path/to/style-mesh/scripts/scannet/render_uv/build/scannet_uv_renderer --out output_path --w 320 --h 240`

Let me know if this solves your issue!

**Comment by pean1128** [comment]
> python render_mipmap_scannet.py --tex /absolute/path/to/tex_0_epoch_6_texture.jpg --mesh /absolute/path/to/scene0291_00_vh_clean_decimate_500000_uvs_blender.ply --poses /absolute/path/to/pose/ --intrinsics /absolute/path/to/scene0291_00.txt --renderer /absolute/path/to/style-mesh/scripts/scannet/render_uv/build/scannet_uv_renderer --out output_path --w 320 --h 240

I confirmed my pose file is the same.  Meanwhile, I tried to render through the python script, but a mismatched result was produced again. This problem may be related to the different runtime platforms or dependencies... I have refactored the rendering function by Open3D render. Later on, I will check in a ubuntu device.

**Comment by lukasHoel** [comment]
So I understand you correctly that _every_ pose is off in comparison to the RGB images? Since we use OpenGL for rendering, it might in fact cause some differences on MacOS. I have no experience with OpenGL on Mac, maybe the coordinate system conventions need to be adjusted, e.g. here: https://github.com/lukasHoel/stylemesh/blob/e31573d1429cc4e1ab472f1a7a2f3eaed4ad19d2/scripts/scannet/render_uv/src/renderer/scannet_renderer.cpp#L36

**Comment by pean1128** [comment]
> So I understand you correctly that _every_ pose is off in comparison to the RGB images? Since we use OpenGL for rendering, it might in fact cause some differences on MacOS. I have no experience with OpenGL on Mac, maybe the coordinate system conventions need to be adjusted, e.g. here:
> 
> https://github.com/lukasHoel/stylemesh/blob/e31573d1429cc4e1ab472f1a7a2f3eaed4ad19d2/scripts/scannet/render_uv/src/renderer/scannet_renderer.cpp#L36

Thanks so much, my coordinate  system is opencv convention. I'll review the details of scannet_renderer.cpp when I have free time.

Now I render my data use a simple pytorch3d render as follows

```    
class SimpleRender(nn.Module):
    device = torch.device("cuda:0")  if torch.cuda.is_available() else torch.device("cpu")

    def __init__(self, meshes, image_size, blend_params=None):
        super().__init__()

        self.raster_settings = RasterizationSettings(
            image_size=image_size,
            blur_radius=0.0,
            faces_per_pixel=1,cull_backfaces=True,cull_to_frustum=True)
    
        self.blend_params = blend_params if blend_params is not None else BlendParams()
        self.meshes = meshes
        self.image_size = image_size
        self.light = None
        self.render = None
        
    def update_view(self, K, W2C):
       R = W2C[:, :3, :3]
        T = W2C[:, :3, -1:]
        T = T.squeeze(2)

        image_size = torch.zeros([1, 2]).to(K)
        image_size[0, 0] = self.image_size[0] # height
        image_size[0, 1] = self.image_size[1] # width
        cameras = cameras_from_opencv_projection(R, T, K, image_size)
        
        self.renderer = MeshRenderer(
            rasterizer=MeshRasterizer(cameras=cameras, raster_settings=self.raster_settings),
            shader=HardPhongShader(device=SimpleRender.device, cameras=cameras)
        )
        #rendered_images = renderer(self.meshes, cameras=cameras, lights=self.lights)    
        
    def forward(self, K, W2C, **kwargs) -> torch.Tensor:        
        self.update_view(K, W2C)
        if self.renderer is not None:
            fragments = self.renderer.rasterizer(self.meshes)
            blend_params = kwargs.get("blend_params", self.blend_params)
            texels = self.meshes.sample_textures(fragments)
            images = hard_rgb_blend(texels, fragments, blend_params)
```

**Comment by lukasHoel** [comment]
Great, let me know if you have further questions any time :)
